//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadioPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Rock Radio
        ///2 Rock Best Ballads
        ///3 Rock Hard &amp; Heavy
        ///4 Rock Classics
        ///5 Radio Center
        ///6 Center TOP 100
        ///7 Center Fresh Pop
        ///8 Kronehit 80 - 90
        ///9 Kronehit Fresh
        ///10 Kronehit Dance
        ///11 Radio 1.
        /// </summary>
        internal static string radio {
            get {
                return ResourceManager.GetString("radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://stream.rockradio.si:9034/;stream/1
        ///http://stream.rockradio.si:9036/;stream/1
        ///http://stream.rockradio.si:9040/;stream/1
        ///http://stream.rockradio.si:9042/;stream/1
        ///http://stream2.radiocenter.si:8000/center
        ///http://stream3.radiocenter.si:9020/;stream/1
        ///http://stream3.radiocenter.si:8058/;stream/1
        ///http://secureonair.krone.at/kronehit-event2.mp3
        ///http://secureonair.krone.at/kronehit-fresh.mp3
        ///http://secureonair.krone.at/kronehit-dance.mp3
        ///http://live.radio1.si/Radio1PR&quot;.
        /// </summary>
        internal static string radio_url {
            get {
                return ResourceManager.GetString("radio_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadioCenter {
            get {
                object obj = ResourceManager.GetObject("RadioCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
